### ISSUE TITLE
imagick using php.ini

### ISSUE THREAD

**Issue by oliversmiths** [CreunaFI/color-space-fixer#6]
Hello, my shared host allows me to enable imagick using a php.ini file.

Unfortunately it appears that this is not enabled on each directory recursively. Therefore when enabled in the main wordpress install directory I received the error `Color Space Fixer is activated but it's not doing anything because ImageMagick PHP extension has not been loaded. How to fix.`

Which directory(s) specifically requires the imagick installed? plugins, uploads, somewhere else?

Many thanks for your work. This plugin will be invaluable to me. I would certainly pay a licence fee for a version which can batch convert existing uploads.

**Comment by joppuyo** [comment]
Hey, I'm not aware that it is possible to enable ImageMagick per directory. Usually, you just install the PHP module and then add `extension=imagick.so` in php.ini so that ImageMagick is available everywhere. But it's possible that your host has some weird way of enabling it. Anyway, you could try enabling ImageMagick in the plugin directory `wp-content/plugins/color-space-fixer`

PS. if you have WordPress 5.2, you can check which image editor WordPress is using by going to Tools -> Site Health -> Info. It should list either Image_Editor_GD or Image_Editor_Imagick under Media Handling.

> I would certainly pay a licence fee for a version which can batch convert existing uploads.

Batch conversion will be coming in the next version of the plugin, I'm working on right now. And it will be free of charge 🙂

**Comment by oliversmiths** [comment]
Thank you kindly for you response. I've followed up further with my hosting provider (Siteground). For anyone experiencing this issue in the future I thought I'd include the response from Siteground, following adding `extension=imagick.so` to php.ini  in the home directory:

> Note that by default the change will be applied only to the current directory in which you created the php.ini file. In case you need to apply the change recursively for the whole site, you can edit the .htaccess file of the site using the File Manager tool and add the following line in it:
> 
> SetEnv PHPRC /home/customer/www/domain.com/public_html/php.ini
> where “domain.com” should be replaced with the actual domain of your site. 

Everything is now working as expected.

Once again, many thanks for this plugin and can't wait to see the batch conversion stuff.

**Comment by joppuyo** [comment]
Hey, great thing you got it to work. I looked into this some more and it does seem that it’s possible to create a php.ini on per-directory basis, I did not know that. So I learned something new today!

Closing this issue for now.
